### ISSUE TITLE
Frodo 4.3 doesn't work on Wayland

### ISSUE THREAD

**Issue by musuruan** [cebix/frodo4#2]
Hi Christian,
    I was testing the Frodo 4.3 RPM I was making for RPM Fusion.

On Fedora 40, it seems that both Frodo and FrodoLite don't work under Wayland. The start up GUI will be displayed and then it will freeze after pressing the "start" button. It only works under X11.

Can you please check?

Kind Regards,

Andrea

**Comment by cebix** [comment]
Can you check whether e4bda36 improves things?

**Comment by musuruan** [comment]
Yes, it now works.

**Comment by cebix** [comment]
Fixed by e4bda36
