### ISSUE TITLE
Problems building a recent version

### ISSUE THREAD

**Issue by Pokefinder-org** [cebix/frodo4#3]
Hello,

trying to build a checkout with Debian 12.7 leads to  "sdl2-config --version' returned 2.26.5" and configure.ac requests 2.30.
Is 2.30 really required?

I changed the 2.30 in configure.ac to 2.26 and autogen went through.
However on "make" I am getting:

make  all-am
make[2]: Entering directory '/Data/frodo4/src'
g++ -std=c++20 -DHAVE_CONFIG_H -I.  -DFRODO_SC -DDATADIR=\"/usr/local/share/Frodo/\" -DHTMLDIR=\"/usr/local/share/doc/Frodo/\" -I/usr/include/SDL2 -D_REENTRANT  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -pthread   -g -O2 -MT Frodo-main.o -MD -MP -MF .deps/Frodo-main.Tpo -c -o Frodo-main.o `test -f 'main.cpp' || echo './'`main.cpp
mv -f .deps/Frodo-main.Tpo .deps/Frodo-main.Po
g++ -std=c++20 -DHAVE_CONFIG_H -I.  -DFRODO_SC -DDATADIR=\"/usr/local/share/Frodo/\" -DHTMLDIR=\"/usr/local/share/doc/Frodo/\" -I/usr/include/SDL2 -D_REENTRANT  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -pthread   -g -O2 -MT Frodo-Display.o -MD -MP -MF .deps/Frodo-Display.Tpo -c -o Frodo-Display.o `test -f 'Display.cpp' || echo './'`Display.cpp
Display.cpp:33:10: fatal error: format: No such file or directory
   33 | #include <format>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [Makefile:564: Frodo-Display.o] Error 1

Do I just miss some dependency? Installed all SDL2 dev packages I could find.

shrug :(

**Comment by cebix** [comment]
It seems you're missing the C++20 &lt;format&gt; header.
GCC 13 should have it.

**Comment by cebix** [comment]
Missing C++ library part. Not a problem of the Frodo code.
