### ISSUE TITLE
4.4. make fails on MacOS 13.7.1

### ISSUE THREAD

**Issue by gorans** [cebix/frodo4#4]
Hi,

make errors out on Ventura. All prerequisites installed.
Config.log and make result attached.

Goran
[make.log](https://github.com/user-attachments/files/17907883/make.log)
[config.log](https://github.com/user-attachments/files/17907884/config.log)

**Comment by cebix** [comment]
Similar to issue #3. You need a C++20 compiler with the <format> library.

**Comment by cebix** [comment]
Maybe autoconf needs to be told explicitly which compiler to use:
`./autogen.sh CXX=g++-13`

**Comment by gorans** [comment]
That worked.
Frodo launched first time but crashed after trying to open settings with F10. Can't launch anymore:
`zsh: segmentation fault  /Users/gogo/Desktop/downld/Frodo-4.4/src/Frodo`
