### ISSUE TITLE
DATADIR and HTMLDIR create hard coded path in binary

### ISSUE THREAD

**Issue by tordona** [cebix/frodo4#5]
Platform: Windows
Environment: msys
Issue: `DATADIR` and `HTMLDIR` value causes a hard coded paths in the compiled binary. This prevents having a portable distributable binary.

example:
```
C:/msys64/clangarm64/share/Frodo/Frodo.ui
```

The executable will run, handling the unavailable preferences UI definition, and display initial screen. However, attempting F10 to open options will cause a crash and exit.

make install gives a file structure of
```
bin
lib
share
```

I've been unable to pass in a relative path for configure as it errors out wanting an absolute path
`configure: error: expected an absolute directory name`

It seems as though `prefs_gtk.h` should use a relative path instead of `DATADIR`
Am not sure about `HTMLDIR` as the file protocol would need to be absolute to open correctly in browser

**Comment by cebix** [comment]
I guess I can make Frodo look in the application base directory first for these files.

**Comment by tordona** [comment]
With latest change, I'm still seeing hard coded path in the binary.

calling
`./autogen.sh --prefix=/d/frodo`

results
`D:/frodo/share/Frodo/Frodo.ui`

calling without prefix
`./autogen.sh`

results
`C:/msys64/clangarm64/share/Frodo/Frodo.ui`

Could it do a runtime path lookup?

**Comment by cebix** [comment]
It does a runtime lookup, using SDL_GetBasePath().

**Comment by tordona** [comment]
I've tested changing the install location locally, something like `Frodo4` or `Emulators\Frodo` and it exhibits the same behavior described above.

`The executable will run, handling the unavailable preferences UI definition, and display initial screen. However, attempting F10 to open options will cause a crash and exit.`

**Comment by cebix** [comment]
No need to install or to specify a prefix. Just put the Frodo.ui file in the same directory as the Frodo executable.

**Comment by tordona** [comment]
> No need to install or to specify a prefix. Just put the Frodo.ui file in the same directory as the Frodo executable.

yup. that works. thanks.

**Comment by cebix** [comment]
The *.html files go into a directory named "docs" in the application directory.

**Comment by tordona** [comment]
Looks like the file protocol needs 3 forwards slashes to work properly. Currently it's being output with only two forwards slashes.

`file://`

The `User Manual` menu item worked fine once I added the missing slash.

**Comment by cebix** [comment]
6824233 should take care of that.
